CREATE DATABASE Gufi_Manha;

USE Gufi_Manha;

CREATE TABLE TipoUsuario(
	ID_TipoUsuario  INT PRIMARY KEY IDENTITY,
	TipoUsuario		VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE TipoEvento(
	ID_TipoEvento	INT PRIMARY KEY IDENTITY,
	TipoEvento		VARCHAR (255) NOT NULL UNIQUE
);

CREATE TABLE Instituicao(
	ID_Instituicao	INT PRIMARY KEY IDENTITY,
	CNPJ			CHAR(14) NOT NULL UNIQUE,
	NomeFantasia	VARCHAR(255) NOT NULL UNIQUE,
	Endereco		VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE Usuarios(
	ID_Usuario		INT PRIMARY KEY IDENTITY,
	NomeUsuario		VARCHAR(255) NOT NULL,
	Email			VARCHAR(255) NOT NULL UNIQUE,
	Senha			VARCHAR(255) NOT NULL,
	DataCadastro	DATETIME2,
	Genero			VARCHAR(255),
	ID_TipoUsuario	INT FOREIGN KEY REFERENCES TipoUsuario (ID_TipoUsuario)
);

CREATE TABLE Eventos(
	ID_Evento		INT PRIMARY KEY IDENTITY,
	NomeEvento		VARCHAR (255) NOT NULL,
	DataEvento		DATETIME2 NOT NULL,
	Descricao		VARCHAR (255) NOT NULL,
	AcessoLivre		BIT DEFAULT (1) NOT NULL,
	ID_Instituicao  INT FOREIGN KEY REFERENCES Instituicao (ID_Instituicao),
	ID_TipoEvento	INT FOREIGN KEY REFERENCES TipoEvento (ID_TipoEvento)
);

CREATE TABLE Presencas(
	ID_Presenca	INT PRIMARY KEY IDENTITY,
	ID_Usuario	INT FOREIGN KEY REFERENCES Usuarios (ID_Usuario),
	ID_Evento	INT FOREIGN KEY REFERENCES Eventos (ID_Evento),
	Situacao	VARCHAR (255) NOT NULL
);