CREATE DATABASE PClinics;

USE PClinics;

CREATE TABLE Clinicas (
	ID_Clinica		INT PRIMARY KEY IDENTITY,
	RazaoSocial		VARCHAR(200),
	Endereco		VARCHAR(200)
);

CREATE TABLE Donos (
	ID_Dono	INT PRIMARY KEY IDENTITY,
	Nome	VARCHAR(200)
);

CREATE TABLE TipoPET (
	ID_TipoPET		INT PRIMARY KEY IDENTITY,
	Titulo			VARCHAR(200)
);

CREATE TABLE Racas (
	ID_Raca		INT PRIMARY KEY IDENTITY,
	Titulo		VARCHAR(200),
	TipoPET		INT FOREIGN KEY REFERENCES TipoPET (ID_TipoPET)
);

CREATE TABLE Veterinarios (
	ID_Vet		INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200),
	CRMV		INT,
	Clinica		INT FOREIGN KEY REFERENCES Clinicas (ID_Clinica)
);

CREATE TABLE PETs (
	ID_Pet		INT PRIMARY KEY IDENTITY,
	Nome		VARCHAR(200),
	Telefone	INT,
	Dono		INT FOREIGN KEY REFERENCES Donos (ID_Dono),
	Raca		INT FOREIGN KEY REFERENCES Racas (ID_Raca)
);

CREATE TABLE Atendimentos (
	ID_Atendimento		INT PRIMARY KEY IDENTITY,
	DataConsulta		DATE,
	Descricao			VARCHAR(200),
	Veterinario			INT FOREIGN KEY REFERENCES Veterinarios (ID_Vet),
	PET					INT FOREIGN KEY REFERENCES PETs (ID_pet)
);